version: '3'
services:
  restaurants:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: db-production
        target: /code/monolith/db
    depends_on:
      - redis
      - worker
    ports:
      - "8080:8080"
    environment:
      - "BROKER=redis://redis:6379"
      - "BACKEND=redis://redis:6379"
      - "CONFIG=PRODUCTION"
  worker:
    build:
      context: .
    environment:
      - "BROKER=redis://redis:6379"
      - "BACKEND=redis://redis:6379"
      - "CONFIG=PRODUCTION"
    command: celery -A monolith.worker:celery worker -l info -B -s /tmp/celerybeat-schedule
    depends_on:
      - redis
    volumes:
      - type: volume
        source: db-production
        target: /code/monolith/db
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
volumes:
  db-production: